title: "Glossary"
repository: <USERNAME>/<PROJECT>
defaults:
- scope:
    path: ""
  values:
    layout: "page"
kramdown:
  toc_levels: "2"
exclude:
- "Makefile"
- "README.md"
- "bin/*"
- "vendor"
languages:
- key: af
  name: Afrikaans
  flag: south-africa
  title: Woordelys
- key: en
  name: English
  title: Glossary
  flag: united-kingdom
  title: Glossary
- key: es
  name: Español
  title: Glossaire
  flag: spain
  title: Glosario
- key: fr
  name: Français
  title: Glosario
  flag: france
  title: Glossaire
- key: zu
  name: IsiZulu
  flag: south-africa
  title: Uhlu Lwamagama
