on: [push, pull_request]

name: Build and Deploy Glossary Website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false

    - name: Build site
      run: make gh-site

    - name: Remove _data fromm .gitignore
      run: "cat .gitignore | grep -v '_data' > .gitignore"

    - name: inspect content of folder
      run: ls -alh _gh-site && ls -alh _gh-site/_data

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_DEPLOY }}
        BRANCH: gh-pages
        FOLDER: _gh-site
        SINGLE_COMMIT: true
